"""Initial schema setup

Revision ID: eb3753c881b7
Revises: 
Create Date: 2026-07-07 04:23:33.625084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from backend.app.db import UTCDateTime


# revision identifiers, used by Alembic.
revision: str = 'eb3753c881b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('external_event_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('processed_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_events_external_event_id'), 'billing_events', ['external_event_id'], unique=True)
    op.create_table('indicator_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('max_subscriptions', sa.Integer(), nullable=False),
    sa.Column('max_timeframes', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('billing_interval', sa.String(length=16), nullable=False),
    sa.Column('whop_plan_id', sa.String(length=64), nullable=True),
    sa.Column('plan_kind', sa.String(length=16), nullable=False),
    sa.Column('addon_bonus_subscriptions', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('whop_plan_id')
    )
    op.create_table('tickers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('yfinance_symbol', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_yfinance_symbol'), 'tickers', ['yfinance_symbol'], unique=True)
    op.create_table('timeframes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('trading_style', sa.String(length=32), nullable=False),
    sa.Column('primary_market', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timeframe_id', sa.Uuid(), nullable=False),
    sa.Column('indicator_type_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tickers_scanned', sa.Integer(), nullable=False),
    sa.Column('trends_found', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_type_id'], ['indicator_types.id'], ),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_customer_id', sa.String(length=128), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('current_period_start', UTCDateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', UTCDateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('bonus_subscriptions', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('timeframe_scan_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timeframe_id', sa.Uuid(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_started_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timeframe_id')
    )
    op.create_table('user_notification_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('discord_webhook_url_enc', sa.String(length=1024), nullable=True),
    sa.Column('telegram_bot_token_enc', sa.String(length=1024), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('preferred_channel', sa.String(length=16), nullable=False),
    sa.Column('delete_previous_messages', sa.Boolean(), nullable=False),
    sa.Column('notify_on', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ticker_id', sa.Uuid(), nullable=False),
    sa.Column('timeframe_id', sa.Uuid(), nullable=False),
    sa.Column('indicator_type_id', sa.Uuid(), nullable=False),
    sa.Column('bars', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_type_id'], ['indicator_types.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker_id', 'timeframe_id', 'indicator_type_id', name='uq_user_sub')
    )
    op.create_table('trend_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_run_id', sa.Uuid(), nullable=False),
    sa.Column('ticker_id', sa.Uuid(), nullable=False),
    sa.Column('timeframe_id', sa.Uuid(), nullable=False),
    sa.Column('indicator_type_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('bars_scanned', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('scanned_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_type_id'], ['indicator_types.id'], ),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_run_id', 'ticker_id', 'timeframe_id', 'indicator_type_id', 'bars_scanned', name='uq_trend_event_per_scan')
    )
    op.create_table('user_plan_addons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('provider_membership_id', sa.String(length=128), nullable=False),
    sa.Column('bonus_subscriptions', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_membership_id')
    )
    op.create_table('notification_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ticker_id', sa.Uuid(), nullable=False),
    sa.Column('timeframe_id', sa.Uuid(), nullable=False),
    sa.Column('bars_scanned', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('external_message_id', sa.String(length=128), nullable=False),
    sa.Column('trend_event_id', sa.Uuid(), nullable=True),
    sa.Column('sent_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], ),
    sa.ForeignKeyConstraint(['trend_event_id'], ['trend_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_messages')
    op.drop_table('user_plan_addons')
    op.drop_table('trend_events')
    op.drop_table('user_subscriptions')
    op.drop_table('user_notification_settings')
    op.drop_table('timeframe_scan_schedules')
    op.drop_table('subscriptions')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('timeframes')
    op.drop_index(op.f('ix_tickers_yfinance_symbol'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_table('plans')
    op.drop_table('indicator_types')
    op.drop_index(op.f('ix_billing_events_external_event_id'), table_name='billing_events')
    op.drop_table('billing_events')
    # ### end Alembic commands ###
